language: generic 
sudo: required
services: 
  - docker

before_install: 
  - docker build -t abhammartech/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhammartech/docker-react npm run test
